[features]
seeds = false

[registry]
url = "https://miyamints.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "program",
]

[toolchain]
anchor_version = "0.28.0"